### ISSUE TITLE
amalgamate/crow_all.h:9551:14: internal compiler error: in write_expression, with gcc 7.3 on Fedora 28

### ISSUE THREAD

**Issue by fangqiao** [ipkn/crow#303]
Recently I am working on a project using crow to expose some REST api.

It used to compile well on archlinux and centos with gcc 7.3.

Now I tested it on fedora 28. With gcc 8 coming with Fedora 28 and then gcc 7.3 I manually installed, such compilation error occured:

```
amalgamate/crow_all.h:9551:14: internal compiler error: in write_expression, at cp/mangle.c:3047
         auto route(std::string&& rule)
              ^~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
```

I understand it is most likely a gcc bug on Fedora 28 environment but I can't wait for a fix from gcc. Is there any  idea how to quickly fix this problem from crow code ?

Thanks,

Update: 

Using clang compilation passed. It is indeed a gcc bug. I leave the issue here for reference.

**Comment by br3gan** [comment]
Same on Arch since GCC 8.1.0 update.

**Comment by khairy-mohamed** [comment]
same problem on arch . any solution !!!!??

**Comment by fangqiao** [comment]
In the original issue:

Update:

Using clang compilation passed. It is indeed a gcc bug. I leave the issue here for reference.

**Comment by khairy-mohamed** [comment]
for someone if need to solve this issue :: 
https://stackoverflow.com/questions/7031126/switching-between-gcc-and-clang-llvm-using-cmake

**Comment by ilejn** [comment]
Is amalgamation required condition to observe this issue? IOW, is anyone who does not use amalgamation seeing this?

**Comment by CircuitCoder** [comment]
For anyone who is using gcc 8 and met this issue, and is willing to use c++1y features, you may change the definition of the route function to use auto return type deduction, and remove the trailing return type.
```c++
template <uint64_t Tag>
auto& route(std::string&& rule)
{
  //...
}
```

Then it should compile with gcc.

**Comment by mwm126** [comment]
Did you get it to build with the above workaround? I am getting an error after removing the trailing return type as suggested above:

```
/usr/bin/c++ --version
c++ (Ubuntu 8.2.0-7ubuntu1) 8.2.0
/usr/bin/c++   -Icrow/include  -std=c++11 -o foo.o -c foo.cpp
In file included from crow/include/crow.h:23,
                 from crow/crowmfix.h:1,
                 from crowmfix.cpp:13:
crow/include/crow/app.h:62:38: error: ‘route’ function uses ‘auto’ type specifier without trailing return type
         auto& route(std::string&& rule)
```

**Comment by nicktrandafil** [comment]
@mwm126 You should use `-std=c++1y`, but not `-std=c++11`

**Comment by mwm126** [comment]
Oh thank you, yeah that worked.

**Comment by ricargoes** [comment]
I had the same problem a while ago and I froze the gcc version I was using. However, I just tried compiling with gcc 9.1.0 and it worked

**Comment by moneroexamples** [comment]
@ricargoes 

Good it worked. Though it does not change the fact that crow is pretty much dead at this point. The last commit was in 2017.

**Comment by sdaveas** [comment]
GCC 9 fixed the error on arch, as well.
