### ISSUE TITLE
crow.h build error

### ISSUE THREAD

**Issue by shahmuratov** [ipkn/crow#131]
Hi! I'm trying to build on Ubuntu 14.04 with g++ 5.3.0 
gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04) 
Keep getting error
```
crow.h:6696:17: error: invalid use of ‘class std::set<typename function_t::arg<Indices>...>’
             ret.template set<
                 ^
```
Corresponding code is

```
auto ret = detail::routing_handler_call_helper::Wrapped<Func, typename function_t::template arg<Indices>...>();
            ret.template set<
                typename function_t::template arg<Indices>...
            >(std::move(f));
```
Before that tried to build with g++ 4.8 with same result
What can I do?

**Comment by shahmuratov** [comment]
So I've figured out what the problem was. I've had using namespace std; before including crow.h. So #include "crow.h" should be at the very beginning of file
