### ISSUE TITLE
Cannot build on boost 1.70

### ISSUE THREAD

**Issue by mattn** [ipkn/crow#340]
```
g++ -std=c++14 -c -I../include -I. helloworld.cpp -o helloworld.o

In file included from ../include/crow.h:7,
                 from helloworld.cpp:1:
../include/crow/socket_adaptors.h: In member function 'boost::asio::io_service& crow::SocketAdaptor::get_io_service()':
../include/crow/socket_adaptors.h:22:28: error: 'boost::asio::ip::tcp::socket' {aka 'class boost::asio::basic_stream_socket<boost::asio::ip::tcp>'} has no member named 'get_io_service'
             return socket_.get_io_service();
                            ^~~~~~~~~~~~~~
../include/crow/app.h:63: confused by earlier errors, bailing out

mingw32-make: *** [Makefile:24: helloworld.o] Error 1

```

**Comment by moneroexamples** [comment]
In one of my project's that user `crow`, the issue was fixed. Can check here:

**Comment by mattn** [comment]
I confirmed the patch fixes this issue. Thank you.

**Comment by mattn** [comment]
Could you please send this patch as pull-request?

**Comment by moneroexamples** [comment]
No problem. PR submitted, though I don't expect it being ever merged. The crow project is pretty much dead at this point.

**Comment by pfeatherstone** [comment]
> No problem. PR submitted, though I don't expect it being ever merged. The crow project is pretty much dead at this point.

Maybe this repo should be maintained on a fork??

**Comment by mrozigor** [comment]
I tried, but have no time to create new things right now. But if you want, you can contribute to my fork and then I'll merge changes ;)
