### ISSUE TITLE
merge_all.py

### ISSUE THREAD

**Issue by 14307130040** [ipkn/crow#72]
'print' is not compatible with python 3 and I met with another
'd = open(os.path.join(header_path, header)).read().decode('utf8')
AttributeError: 'str' object has no attribute 'decode''. I've tried to remove the '.decode('utf8')' and seemly solved it.
Beyond this issue, I finally met with 'crow/tests/unittest.cpp:936:46: error: call of overloaded ‘move(const crow::query_string&)’ is ambiguous
         last_url_params = move(req.url_params);
                                              ^
'
build with GNU Make 4.1, g++ (GCC) 5.1.0, Python 3.4.3, boost 1.58.0 on archlinux with kernel version 4.0.5, x86_64 arch

**Comment by marcbarbosa** [comment]
@14307130040 I was getting the same issue with the ambiguous call to `move()` function on OSX 10.10.3.
So, I've added `boost` namespace on the line [936](https://github.com/ipkn/crow/blob/master/tests/unittest.cpp#L936) and now it works:
```php
last_url_params = boost::move(req.url_params);
```

**Comment by 14307130040** [comment]
Thank you and it works. @marcbarbosa
