### ISSUE TITLE
Cannot build on MacOSX 10.10 (Yosemite)

### ISSUE THREAD

**Issue by reinkim** [ipkn/crow#32]
Build failed on MacOSX 10.10 (Yosemite; beta).
## Build Environment
- uname -a: Darwin hermes 14.0.0 Darwin Kernel Version 14.0.0: Sat Sep 27 03:58:47 PDT 2014; root:xnu-2782.1.97~11/RELEASE_X86_64 x86_64 i386 MacBookAir5,2 Darwin
- clang: Apple LLVM version 6.0 (clang-600.0.51) (based on LLVM 3.5svn)
- boost: stable 1.56.0, HEAD (installed using homebrew)
## Build log

```
[ 75%] Building CXX object examples/CMakeFiles/example_chat.dir/example_chat.cpp.o
/Users/rein/work/crow/examples/example_chat.cpp:18:15: error: use of overloaded
      operator '=' is ambiguous (with operand types 'crow::json::wvalue' and
      'size_type' (aka 'unsigned long'))
    x["last"] = msgs.size();
    ~~~~~~~~~ ^ ~~~~~~~~~~~
/Users/rein/work/crow/include/json.h:1118:21: note: candidate function
            wvalue& operator = (bool value)
                    ^
/Users/rein/work/crow/include/json.h:1128:21: note: candidate function
            wvalue& operator = (double value)
                    ^
/Users/rein/work/crow/include/json.h:1136:21: note: candidate function
            wvalue& operator = (uint16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1144:21: note: candidate function
            wvalue& operator = (int16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1152:21: note: candidate function
            wvalue& operator = (uint32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1160:21: note: candidate function
            wvalue& operator = (int32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1168:21: note: candidate function
            wvalue& operator = (uint64_t value)
                    ^
/Users/rein/work/crow/include/json.h:1176:21: note: candidate function
            wvalue& operator = (int64_t value)
                    ^
/Users/rein/work/crow/examples/example_chat.cpp:47:19: error: use of overloaded
      operator '=' is ambiguous (with operand types 'crow::json::wvalue' and
      'size_type' (aka 'unsigned long'))
        x["last"] = msgs.size();
        ~~~~~~~~~ ^ ~~~~~~~~~~~
/Users/rein/work/crow/include/json.h:1118:21: note: candidate function
            wvalue& operator = (bool value)
                    ^
/Users/rein/work/crow/include/json.h:1128:21: note: candidate function
            wvalue& operator = (double value)
                    ^
/Users/rein/work/crow/include/json.h:1136:21: note: candidate function
            wvalue& operator = (uint16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1144:21: note: candidate function
            wvalue& operator = (int16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1152:21: note: candidate function
            wvalue& operator = (uint32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1160:21: note: candidate function
            wvalue& operator = (int32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1168:21: note: candidate function
            wvalue& operator = (uint64_t value)
                    ^
/Users/rein/work/crow/include/json.h:1176:21: note: candidate function
            wvalue& operator = (int64_t value)
                    ^
/Users/rein/work/crow/examples/example_chat.cpp:60:23: error: use of overloaded
      operator '=' is ambiguous (with operand types 'crow::json::wvalue' and
      'size_type' (aka 'unsigned long'))
            x["last"] = msgs.size();
            ~~~~~~~~~ ^ ~~~~~~~~~~~
/Users/rein/work/crow/include/json.h:1118:21: note: candidate function
            wvalue& operator = (bool value)
                    ^
/Users/rein/work/crow/include/json.h:1128:21: note: candidate function
            wvalue& operator = (double value)
                    ^
/Users/rein/work/crow/include/json.h:1136:21: note: candidate function
            wvalue& operator = (uint16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1144:21: note: candidate function
            wvalue& operator = (int16_t value)
                    ^
/Users/rein/work/crow/include/json.h:1152:21: note: candidate function
            wvalue& operator = (uint32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1160:21: note: candidate function
            wvalue& operator = (int32_t value)
                    ^
/Users/rein/work/crow/include/json.h:1168:21: note: candidate function
            wvalue& operator = (uint64_t value)
                    ^
/Users/rein/work/crow/include/json.h:1176:21: note: candidate function
            wvalue& operator = (int64_t value)
                    ^
3 errors generated.
make[2]: *** [examples/CMakeFiles/example_chat.dir/example_chat.cpp.o] Error 1
make[1]: *** [examples/CMakeFiles/example_chat.dir/all] Error 2
make: *** [all] Error 2
```
