### PR TITLE
Update merge_all to run with python 3.

### LINKED ISSUE #72: merge_all.py
'print' is not compatible with python 3 and I met with another
'd = open(os.path.join(header_path, header)).read().decode('utf8')
AttributeError: 'str' object has no attribute 'decode''. I've tried to remove the '.decode('utf8')' and seemly solved it.
Beyond this issue, I finally met with 'crow/tests/unittest.cpp:936:46: error: call of overloaded ‘move(const crow::query_string&)’ is ambiguous
         last_url_params = move(req.url_params);
                                              ^
'
build with GNU Make 4.1, g++ (GCC) 5.1.0, Python 3.4.3, boost 1.58.0 on archlinux with kernel version 4.0.5, x86_64 arch

### PR DESCRIPTION
**Pull request by MartiUK**
parens for ```print()``` and remove ```.decode('utf-8')```

I've also formatted it slightly.

Fixes #72

### CODE REVIEW

**Comment by ipkn** [comment]
Thank you for the work.
